version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.2.0
    steps:
      - checkout
      - run: echo "NPM Installing"
      - run: npm install
      - run: #create env var
          name: "Setting up env var CI and run build"
          command: npm run build
          environment:
            CI: true
  test:
    docker:
      - image: cimg/node:15.2.0
    steps:
      - checkout
      - run: echo "testing"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: cimg/node:15.2.0
    steps:
      - checkout
      - run: echo "Hi there!"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test: #test jobs requires hithere to finish first
          requires:
            - hithere
